### ISSUE TITLE
Is there a way to set a weekend as a working day ?

### ISSUE THREAD

**Issue by chandu188** [rickar/cal#25]

**Comment by rickar** [comment]
Yes, you can use SetWorkday to customize which days are treated as working days.

**Comment by chandu188** [comment]
Ok. But my use case is more than that I guess. Maybe I could explain better with an example.
In general, Saturday and Sunday would be a nonworking day, but I would like to set 9th and 10th of March as a Working day even though those 2 days are Saturday and Sunday. 
In general, I would need a feature which marks a particular weekend as a working day. Is this possible, if so could you please point me out, how to do it? If not, would it make sense to incorporate such a feature?

**Comment by rickar** [comment]
That makes sense. Technically you could have done that by setting weekends as working days globally and then looping over the whole year to add most weekends as holidays. But instead I made the ability to pass a `WorkdayFn` to the calendar which can be used to calculate workdays instead of using the fixed day of week flags.

There is a simple example now in cal_test.go:

```go
        c.WorkdayFunc = func(date time.Time) bool {
		return date.Weekday() == time.Monday ||
			date.Weekday() == time.Tuesday ||
			date.Weekday() == time.Wednesday ||
			(date.Month() == time.March && (date.Day() == 9 || date.Day() == 10))
	}
```

**Comment by chandu188** [comment]
Thank you for the quick resolution !! Will check it out.
