### ISSUE TITLE
Observance should be locale dependant

### ISSUE THREAD

**Issue by HHK1** [rickar/cal#34]
Default for the Observant property is to match US Holidays

For other countries, this option must be manually overriden, which requires knowledge of this behaviour for each country.

`c.Observed = cal.ObservedExact`

Shouldn't this be part of the Holiday object instead ?

**Comment by rickar** [comment]
I think given what I know now, the default should be ObservedExact. A per country or holiday setting would still have to be able to be overridden because individual businesses can choose to set their own policies. Unfortunately this is a breaking change though so it should probably wait until some other major change to go in.

**Comment by HHK1** [comment]
> I think given what I know now, the default should be ObservedExact. 

Yes agreed, that seems to be the norm

> A per country or holiday setting would still have to be able to be overridden because individual businesses can choose to set their own policies.

Yep, as long as you can change it on the holiday object and not the calendar.

Anyway, thanks for the great lib, will keep an eye on the next major update !
