### ISSUE TITLE
Can you clarify the `isHoliday` function on v2?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [rickar/cal#56]
Hi (and a happy new year),
the signature for `isHoliday` is the following:

```
func (c *Calendar) IsHoliday(date time.Time) (actual, observed bool, h *Holiday) {
```

can you please clarify what is the difference between `actual` and `observed`? 
In my tests, using the several `us`, `ca` etc... calendar, it seems for me it's a vacation (as in you don't work) when `actual` is true.

When should I consider `observed`?

Thank you!

**Comment by dherbst** [comment]
Observed is used if you want to know if a workday that is affected by a holiday.   For example, New Year's Day is always on January 1st which is the `actual` date.   The `observed` date is not on January 1st if the 1st falls on a weekend.  There is an offset specified when creating the holiday to move the `observed` date to either the prior or later weekday like here https://github.com/rickar/cal/blob/master/v2/us/us_holidays.go#L14-L20

One time you would consider `observed` is when you are building a plan and have to account for a non-work weekday because of a holiday.

**Comment by rickar** [comment]
@dherbst is correct. `actual` is always the exact date the holiday occurs, such as if you were making a paper calendar and highlighting the holidays -- Christmas is always Dec 25th for example. In some cases, businesses and/or governments will give people a day off of work if a holiday falls on a weekend, so if Christmas happened to occur on a Saturday, in some places businesses would be closed on Friday or Monday to "observe" that holiday instead and that's what `observed` represents.

**Comment by invasionofsmallcubes** [comment]
One last clarification. The compatible approach with the old method is the OR of actual and observed?

**Comment by rickar** [comment]
It depends on your use case. The old `Calendar.IsHoliday()` is like checking `actual` only and the old `Calender.IsWorkday()` is like checking `observed` only. In general, if you are using the calendar to set up business days then you would always check `observed` which will be the same as `actual` unless there are special rules set up for the holiday.
