### ISSUE TITLE
Add an easy way to calculate the day after a weekday offset holiday

### ISSUE THREAD

**Issue by dherbst** [rickar/cal#57]
Some US states or companies include the day after Thanksgiving as a holiday.  In 2024 Thanksgiving is on the 4th Thursday, but the Day After Thanksgiving is on the 5th Friday.  See:

```
$ cal -m 11 2024
   November 2024      
Su Mo Tu We Th Fr Sa  
                1  2  
 3  4  5  6  7  8  9  
10 11 12 13 14 15 16  
17 18 19 20 21 22 23  
24 25 26 27 28 29 30  
```

Please consider adding CalcDayAfterWeekdayOffset to allow for this situation.

**Comment by dherbst** [comment]
I have added PR #58 for this, please take a look.

**Comment by rickar** [comment]
Good catch. Since it may be necessary to have other holidays that are relative to existing ones, I think it would be cleaner to add a new field to Holiday that represents an offset to apply after doing the calculation. That way we don't end up with CalcDayAfterWeekdayOffset, CalcDayBeforeWeekdayOffset, CalcTwoDaysAfterWeekdayOffset, etc. Something like Holiday.CalcOffset? Then it would be applied globally in Holiday.Calc() for any HolidayFn.

**Comment by dherbst** [comment]
There is a field on `Holiday` named `Offset`, so I created a new one named `OffsetDays`.   I only applied the calculation to the actual, not the observed because I'm not sure an observed alteration would make sense.  What do you think of this update in #58 ?
